### PR TITLE
Ticket1268 Add GUI system tests

### PR DESCRIPTION
**Pull request by simonfernandes**
ISISComputingGroup/IBEX/issues/1268

### CODE REVIEW

**Comment by AdrianPotter** [comment]
I've been through an reviewed. There are a couple of points.
1. The new tests haven't been added to the "AllTests" test suite and so aren't currently being run by Jenkins
2. When I added the tests to the test suite and ran locally, the "AddMultipleBlocksToMultipleGroups" and "BlockWithoutGroupGoesIntoOther" tests failed. This may be because other tests aren't functioning in isolation.

Before merging, please could you address the above points and make sure that the tests are passing on the System Tests pull request build:

http://epics-jenkins.isis.rl.ac.uk/job/System_Tests_build_PR/

I have moved the ticket back to In Progress whilst awaiting the fix.

Thanks.

**Comment by simonfernandes** [comment]
Apologies for the many commits! This ticket turned into a pretty big one.

Since the last review, I have mainly been stripping out (and adding) commonly used procedures into the "ConfigProcedures" and "SynopticProcedures" contexts, streamlining the code in the process. I have also removed all deletion or undo routines now that we have John's magic context. All tests have been added to the AllTests suite and pass.

**Comment by DominicOram** [comment]
Jenkins retest this please

**Comment by DominicOram** [comment]
Jenkins retest this please

**Comment by DominicOram** [comment]
Jenkins retest this please

**Pull request merged**
