### PR TITLE
Ticket1377 block log settings system tests

### PR DESCRIPTION
**Pull request by AdrianPotter**

### CODE REVIEW

**Comment by AdrianPotter** [comment]
Note that until the PR for ticket #1165 is merged into master, the PR build of the system tests is liable to fail.

**Comment by AdrianPotter** [comment]
Jenkins retest this please

**Comment by DominicOram** [comment]
Can these be updated to:
- [x] Fix merge conflicts
- [x] Use some of the new config procedures
- [x] Not use a machine specific PV

**Comment by DominicOram** [comment]
Jenkins retest this please

**Comment by DominicOram** [comment]
Jenkins retest this please

**Comment by DominicOram** [comment]
Jenkins retest this please

**Pull request merged**
