### PR TITLE
Ticket1766: Ampersands in titles

### PR DESCRIPTION
**Pull request by DominicOram**
### Description of work

Added some tests for titles and users

### To test

See https://github.com/ISISComputingGroup/IBEX/issues/1766

---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] Does the code make use of existing procedures where appropriate?
- [ ] Do they test a minimal set of functionality and leave the gui as close as possible to its original state?
- [ ] Does the name of the tests reflect what is actually being tested?
- [ ] Has the [manual system tests spreadsheet](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-system-tests) been updated to have entries equivalent to the system tests affected?

### Functional Tests

- [ ] Do the new tests pass on a GUI build containing the fix?
- [x] Do the new tests fail on a GUI build NOT containing the fix (e.g. master)?

### CODE REVIEW

**Comment by DominicOram** [comment]
Note, the title test does not leave the GUI in it's original state. In this case I am unsure what the original state would be and as we have no tests relating to the title I have set it to be blank.

**Comment by Tom-Willemsen** [comment]
System test failed; I think it's because the initial state isn't what it expected. It looks like your code is doing the right thing though.

Is there a way to get it to pass consistently?

```
Assertion of caption failed: expected:<Oram and Ampersand&> but was:<Ampersand&, DEFAULT_USER_1 and Oram>.
	at verify-true (/IBEX_System_Tests/ModifyingUsersIsReflectedOnDashboard.test:20)
```

**Comment by AdrianPotter** [comment]
Sorry Tom, I got trigger happy. I thought this was a legacy system test that hadn't been merged along with original ticket. I don't think it's worth reverting the merge, but please do check that it works with the latest version of the code and request any further changes if necessary.

**Comment by Tom-Willemsen** [comment]
System test still not passing.

```
Assertion of caption failed: expected:<Oram and Ampersand&> but was:<Ampersand&, DEFAULT_USER_1 and Oram>.
	at verify-true (/IBEX_System_Tests/ModifyingUsersIsReflectedOnDashboard.test:20)
```

**Pull request merged**
